spring:
  thymeleaf:
    # 不可缓存
    cache: false

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=UTC&useUnicode=ture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      # 连接池名字
      pool-name: Datapool
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲超时时间，默认600000（10min)
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 自动提交
      auto-commit: true
      # 连接超时时间，默认30000（30s）
      connection-timeout: 30000
      # 测试连接是否可用语句
      connection-test-query: SELECT 1

  # redis设置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

mybatis-plus:
  # 配置mapper.xml映射文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类别名(默认别名是类名）
  type-aliases-package: com.pang.seckill.pojo

# mybatis sql 打印(方法接口所在的包，不是mapper映射文件的包）
logging:
  level:
    com.pang.seckill.mapper: debug
